### ISSUE TITLE
Any way to set game resolution using Splitscreen_Settings.xml?

### ISSUE THREAD

**Issue by burkostya** [DeadlySurprise/FO2-Splitscreen#12]

**Comment by justalex95** [comment]
hey man dont know if your still looking for a resolution fix but here goes...

this is for a 1080p screen, you'll have to make the height half your vertical res (1080p becomes 540p for each window) and keep the width whatever your full horizontal res is (1920) it makes it super widescreen but it fills the whole screen. I'm having a problem with getting the connection between host and client to work, it keeps saying the game doesnt exist anymore and wont let me connect at all so I've not even went ingame with this mod yet. hope this helps
 

<?xml version="1.0"?>
<Settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <InstanceCount>2</InstanceCount>
  <VirtualHostPort>23758</VirtualHostPort>
  <VirtualAddressOffset>1</VirtualAddressOffset>
  <AttachConsole>false</AttachConsole>
  <AttachConsole>false</AttachConsole>
  <WindowPos>{x:0 y:0 width:1920 height:540}</WindowPos>
  <WindowPos>{x:0 y:540 width:1920 height:540}</WindowPos>
  <Controllers>00000000-0000-0000-0000-000000000000</Controllers>
  <Controllers>00000000-0000-0000-0000-000000000000</Controllers>
  <VirtualAddressRange>192.168.80.0</VirtualAddressRange>
  <UseInputEmulation>false</UseInputEmulation>
  <SkipIntros>true</SkipIntros>
</Settings>
