### ISSUE TITLE
Launcher.exe

### ISSUE THREAD

**Issue by DeadSonRisingxD** [DeadlySurprise/FO2-Splitscreen#2]
Is there simple I am missing? I can't find "launcher.exe" within the download?

**Comment by MorMund** [comment]
[The download](https://github.com/DeadlySurprise/FO2-Splitscreen/releases/download/v0.1/FO2_Splitscreen.zip) contains two files, the launcher.exe and flatout2.dll. Maybe you accidentally downloaded the source code archive instead.

**Comment by DeadSonRisingxD** [comment]
Ahh yes I did :D Thank you for the link!
