### ISSUE TITLE
Player not getting input

### ISSUE THREAD

**Issue by gabsF** [DeadlySurprise/FO2-Splitscreen#24]
i set up the key bindings on second player, but it dosent receive the inputs, unless if i click on second player's screen, but the host dosent receive the inputs from the keyboard, what should i do about this? probably i did something wrong and didn't understand the instructions, sorry. also, i'm using the Xbox One Controller

**Comment by MorMund** [comment]
Currently only one game instance can receive keyboard input. I opened two separate feature request (#25 #26) related to this problem. However I don't know yet when I will work on them.  
In the meantime, I am open to suggestions on how the instructions could be improved, especially around the concept of the multiple instances and how to configure them.
