### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by falefee** [DeadlySurprise/FO2-Splitscreen#3]
This is really frustrating. 
![flatout2_2017-11-04_17-57-13](https://user-images.githubusercontent.com/17464649/32410237-b992a340-c189-11e7-8620-825284e3f8d4.png)

[Splitscreen_Settings.zip](https://github.com/DeadlySurprise/FO2-Splitscreen/files/1443634/Splitscreen_Settings.zip)

**Comment by sebghub** [comment]
Hey I got something similar and it was because I was using a widescreen mod. Deleting those files solved it.

**Comment by MorMund** [comment]
It would be great if @falefee could confirm that it was indeed incompatibility with the widescreen mod that caused the crash.   
@sebghub I assume the mod comes as a dinput8.dll file? If so I'll add a warning in the next Version.

**Comment by Wickersun** [comment]
Hi! Unfortunatelly, the widescreen mod is not the main reason. I' ve got the same error as @falefee but my installation is clean, no mods at all (on Windows 7 x64).

**Comment by falefee** [comment]
Yeah, I am using the normal game with only FOJ mods.

**Comment by falefee** [comment]
I have tried using no mods but still this error happens.

**Comment by MorMund** [comment]
I tested the mod on Windows 7 so that shouldn't be the cause.

Can you try installing the [Visual C++ 2017 redistributable](https://go.microsoft.com/fwlink/?LinkId=746571) ?

Other than that which version of the game are you running? I could only test the game with the steam and German retail version. The international retail version contains DRM as far as I know so that might mess with the mod. So if anyone has access to the steam or other DRM version they could check that.

If that isn't the cause either we'll have to until I can improve the error reporting.

**Comment by falefee** [comment]
English retail version (?) with DRM free exe. Can't install 2017 as it
comes with Windows 10

**Comment by MorMund** [comment]
Thank you for helping track down this issue.

Could you try [this build](https://mega.nz/#!ER0QEJTQ!8gjTWOGTvzomirp9Pp0T9hRhpaA8b4wvwxl-B4PzZrs)? It should show more information about the crash.

Additionally if you feel up for it you could create a crash dump with [ProcDump](https://download.sysinternals.com/files/Procdump.zip). (Run `.\procdump.exe FlatOut2.exe` after the error message shows.)

**Comment by falefee** [comment]
This is what comes up now: https://i.imgur.com/D2zizbj.png

**Comment by MorMund** [comment]
OK the error seems to be that the DirectX device can't be created.
[This build](https://mega.nz/#!8BNFFLgA!BSHjv50uPnnPjy6hXNwe9hucTxAX7rSTPZ3iO87P7NA) should give you an error message when the creation fails and create a file called d3derror.txt with more information. If it is a DirectX error we should be close to solving this.

**Comment by falefee** [comment]
Alright, sorry for the late response. Here is the error
https://i.imgur.com/CuaKTGb.png, then the one before follows. My log has :

Error log CDirect3D9Hook::CreateDevice.
HRESULT : -2005530516
Adapter : 0
DeviceType : 1
hFocusWindow : 0034106C
BehaviorFlags : 80
pPresentationParameters : 008DA410
ppReturnedDeviceInterface : 008DA788
Presentation Parameters :
BackBufferWidth : 1920
BackBufferHeight : 1080
BackBufferFormat : 22
BackBufferCount : 2
MultiSampleType : 8
MultiSampleQuality : 0
SwapEffect : 1
hDeviceWindow : 0034106C
Windowed : 1
EnableAutoDepthStencil : 1
AutoDepthStencilFormat : 77
Flags : 0
FullScreen_RefreshRateInHz : 60

**Comment by MorMund** [comment]
> Alright, sorry for the late response.

No worries.
The crash could be caused by `FullScreen_RefreshRateInHz : 60` which is illegal for windowed applications. 
[This build](https://mega.nz/#!QJcQCIKB!Keg3tAIsIU-QAlO7f9G7y1ZkNTKxuETocWLE_iS6X6c) sets it to zero, hopefully we've got the fix!

**Comment by falefee** [comment]
Late again, lol.

It works though, awesome! Thanks for the help.
[image: Inline image 1]
