### ISSUE TITLE
Solution for the Xone controller issue

### ISSUE THREAD

**Issue by R4lco** [DeadlySurprise/FO2-Splitscreen#32]
Hi, I didn't know where to contact you.

Here's the solution for said problem:
"open up Device Manager, expand "Human Interface Devices", right click "XINPUT compatible HID device", "Update driver", "Browse my computer", "Let me pick". should be three options, I tested "HID-compliant game controller". if you want to undo the change, same thing but update "HID-compliant game controller" and pick the XINPUT one"

I tried and it worked :)

**Comment by MorMund** [comment]
Thanks for letting me know about this workaround! I reposted your answer in the issue concerning the Xbox One controller issue #30.
