### ISSUE TITLE
Splitscreen_settings.xml how do I find the controller ID to add?

### ISSUE THREAD

**Issue by sebghub** [DeadlySurprise/FO2-Splitscreen#4]
Hey, the mod isn't working properly for me. The windows are not making use of my screen resolution and some of them are outside of the screen. I can fix this by using the splitscreen_settings.xml but I don't know how to add controllers. Do you know how I can find the ID that is needed instead "0000000x0000x0000x0000x000000" to map controllers to players?

And thanks for making this mod!

**Comment by MorMund** [comment]
Sadly these IDs are only used by Direct Input as far as I know, so there is no easy way to get them. I fixed the settings only containing zeros as ids but it will be a while until I release the next full version. But if you want you can try a [current dev build](https://mega.nz/#!UI9kFL4K!7yZVISACLFEErig1RIgrSKST0sHB1X7wKN253GDS1PI) but other things might be broken.

**Comment by sebghub** [comment]
ok thanks
