### ISSUE TITLE
Steam Controller Support

### ISSUE THREAD

**Issue by kuznet1** [DeadlySurprise/FO2-Splitscreen#6]
I have launched Launcher.exe through Steam app, but I do not see my gamepads in Controllers tab

**Comment by MorMund** [comment]
Can you use the steam controller in the regular game without the launcher?

**Comment by kuznet1** [comment]
I recently tried to use the steam controller as gamepad without the launcher and I did not succeed. It succeeded only in [keyboard emulation mode](https://www.steamcontrollerdb.com/config/flatout-2/martzooks-flatout-2-bindings/2465) (as far as I understand). Unfortunately, this is "Won't fix".
